-- Generated by Mocodo 4.3.2

CREATE TABLE aeroport (
  PRIMARY KEY (id_aeroport),
  id_aeroport VARCHAR(42) NOT NULL,
  nom         VARCHAR(42),
  ville       VARCHAR(42),
  pays        VARCHAR(42)
);

CREATE TABLE companie (
  PRIMARY KEY (id_companie),
  id_companie VARCHAR(42) NOT NULL,
  nom_comp    VARCHAR(42)
);

CREATE TABLE localiser (
  PRIMARY KEY (id_companie, id_aeroport),
  id_companie VARCHAR(42) NOT NULL,
  id_aeroport VARCHAR(42) NOT NULL
);

CREATE TABLE terminal (
  PRIMARY KEY (id_terminal),
  id_terminal VARCHAR(42) NOT NULL,
  nom         VARCHAR(42),
  id_aeroport VARCHAR(42) NOT NULL
);

CREATE TABLE vol (
  PRIMARY KEY (id_vol),
  id_vol              VARCHAR(42) NOT NULL,
  nom_vol             VARCHAR(42),
  date_heure_depart_1 VARCHAR(42),
  correspondance      VARCHAR(42),
  id_terminal_1       VARCHAR(42) NOT NULL,
  date_heure_arrivee  VARCHAR(42),
  id_terminal_2       VARCHAR(42) NOT NULL,
  date_heure_depart_2 VARCHAR(42),
  id_companie         VARCHAR(42) NOT NULL
);

ALTER TABLE localiser ADD FOREIGN KEY (id_aeroport) REFERENCES aeroport (id_aeroport);
ALTER TABLE localiser ADD FOREIGN KEY (id_companie) REFERENCES companie (id_companie);

ALTER TABLE terminal ADD FOREIGN KEY (id_aeroport) REFERENCES aeroport (id_aeroport);

ALTER TABLE vol ADD FOREIGN KEY (id_companie) REFERENCES companie (id_companie);
ALTER TABLE vol ADD FOREIGN KEY (id_terminal_2) REFERENCES terminal (id_terminal);
ALTER TABLE vol ADD FOREIGN KEY (id_terminal_1) REFERENCES terminal (id_terminal);
