from .extensions import db
from .models import *
from .myapp import app
from datetime import datetime

@app.cli.command()
def syncdb():
    db.create_all()
    db.session.query(Compagnie).delete()
    db.session.query(Aeroport).delete()
    db.session.query(Localiser).delete()
    db.session.query(Terminal).delete()
    db.session.query(Vol).delete()
    db.session.query(Partir).delete()
    db.session.query(Arriver).delete()
    compagnie1 = Compagnie(nom_comp = "Air France")
    compagnie2 = Compagnie(nom_comp = "Corendon")
    compagnie3 = Compagnie(nom_comp = "Corsair")
    aeroport1 = Aeroport(nom_aeroport = "Charles de Gaulle", ville= "Roissy", pays="France")
    aeroport2 = Aeroport(nom_aeroport = "Aéroport de Londres-Heathrow", ville= "Hounslow", pays="Royaume-Uni")
    aeroport3 = Aeroport(nom_aeroport = "Aéroport de Francfort", ville= "Francfort", pays="Allemagne")
    db.session.add(compagnie1)
    db.session.add(compagnie2)
    db.session.add(compagnie3)
    db.session.add(aeroport1)
    db.session.add(aeroport2)
    db.session.add(aeroport3)
    db.session.commit()
    localiser1  = Localiser(id_aeroport=1, id_compagnie=1)
    localiser2  = Localiser(id_aeroport=2, id_compagnie=2)
    localiser3  = Localiser(id_aeroport=2, id_compagnie=1)
    localiser4  = Localiser(id_aeroport=3, id_compagnie=3)
    db.session.add(localiser1)
    db.session.add(localiser2)
    db.session.add(localiser3)
    db.session.add(localiser4)
    db.session.commit()
    terminal1 = Terminal(nom_terminal = "Terminal 1", id_aeroport=1)
    terminal2 = Terminal(nom_terminal = "Terminal 2A", id_aeroport=1)
    terminal3 = Terminal(nom_terminal = "Terminal 2B", id_aeroport=1)
    terminal4 = Terminal(nom_terminal = "Terminal 2C", id_aeroport=1)
    terminal5 = Terminal(nom_terminal = "Terminal 2", id_aeroport=2)
    terminal6 = Terminal(nom_terminal = "Terminal 3", id_aeroport=2)
    terminal7 = Terminal(nom_terminal = "Terminal 4", id_aeroport=2)
    terminal8 = Terminal(nom_terminal = "Terminal 5", id_aeroport=2)
    terminal9 = Terminal(nom_terminal = "Terminal 1", id_aeroport=3)
    terminal10 = Terminal(nom_terminal = "Terminal 2", id_aeroport=3)
    db.session.add(terminal1)
    db.session.add(terminal2)
    db.session.add(terminal3)
    db.session.add(terminal4)
    db.session.add(terminal5)
    db.session.add(terminal6)
    db.session.add(terminal7)
    db.session.add(terminal8)
    db.session.add(terminal9)
    db.session.add(terminal10)
    db.session.commit()
    vol1 = Vol(nom_vol = "AF123", id_compagnie=1)
    vol2 = Vol(nom_vol = "AF456", id_compagnie=1)
    vol3 = Vol(nom_vol = "CR789", id_compagnie=2)
    vol4 = Vol(nom_vol = "CR101", id_compagnie=2)
    vol5 = Vol(nom_vol = "CS112", id_compagnie=3)
    vol6 = Vol(nom_vol = "CS131", id_compagnie=3)
    db.session.add(vol1)
    db.session.add(vol2)
    db.session.add(vol3)
    db.session.add(vol4)
    db.session.add(vol5)
    db.session.add(vol6)
    db.session.commit()
    partir1 = Partir(id_terminal=1, id_vol=1, date_heure_depart=datetime.strptime("2024-07-01 08:00:00", "%Y-%m-%d %H:%M:%S"))
    partir2 = Partir(id_terminal=2, id_vol=2, date_heure_depart=datetime.strptime("2024-07-01 09:00:00", "%Y-%m-%d %H:%M:%S"))
    partir3 = Partir(id_terminal=5, id_vol=3, date_heure_depart=datetime.strptime("2024-07-01 10:00:00", "%Y-%m-%d %H:%M:%S"))
    partir4 = Partir(id_terminal=6, id_vol=4, date_heure_depart=datetime.strptime("2024-07-01 11:00:00", "%Y-%m-%d %H:%M:%S"))
    partir5 = Partir(id_terminal=9, id_vol=5, date_heure_depart=datetime.strptime("2024-07-01 12:00:00", "%Y-%m-%d %H:%M:%S"))
    partir6 = Partir(id_terminal=10, id_vol=6, date_heure_depart=datetime.strptime("2024-07-01 13:00:00", "%Y-%m-%d %H:%M:%S"))
    db.session.add(partir1)
    db.session.add(partir2)
    db.session.add(partir3)
    db.session.add(partir4) 
    db.session.add(partir5)
    db.session.add(partir6)
    db.session.commit()
    arriver1 = Arriver(id_terminal=5, id_vol=1, date_heure_arrivee=datetime.strptime("2024-07-01 10:00:00", "%Y-%m-%d %H:%M:%S"))
    arriver2 = Arriver(id_terminal=6, id_vol=2, date_heure_arrivee=datetime.strptime("2024-07-01 11:00:00", "%Y-%m-%d %H:%M:%S"))
    arriver3 = Arriver(id_terminal=1, id_vol=3, date_heure_arrivee=datetime.strptime("2024-07-01 12:00:00", "%Y-%m-%d %H:%M:%S"))
    arriver4 = Arriver(id_terminal=2, id_vol=4, date_heure_arrivee=datetime.strptime("2024-07-01 13:00:00", "%Y-%m-%d %H:%M:%S"))
    arriver5 = Arriver(id_terminal=9, id_vol=5, date_heure_arrivee=datetime.strptime("2024-07-01 14:00:00", "%Y-%m-%d %H:%M:%S"))
    arriver6 = Arriver(id_terminal=10, id_vol=6, date_heure_arrivee=datetime.strptime("2024-07-01 15:00:00", "%Y-%m-%d %H:%M:%S"))
    db.session.add(arriver1)
    db.session.add(arriver2)
    db.session.add(arriver3)
    db.session.add(arriver4)
    db.session.add(arriver5)
    db.session.add(arriver6)
    db.session.commit()
