from .extensions import db
from .models import *
from .myapp import app

@app.cli.command()
def syncdb():
    db.create_all()
    db.session.query(Companie).delete()
    db.session.query(Aeroport).delete()
    db.session.query(Localiser).delete()
    db.session.query(Terminal).delete()
    db.session.query(Vol).delete()
    db.session.query(Partir).delete()
    db.session.query(Arriver).delete()
    companie1 = Companie(nom_comp = "Air France")
    companie2 = Companie(nom_comp = "Corendon")
    companie3 = Companie(nom_comp = "Corsair")
    aeroport1 = Aeroport(nom_aeroport = "Charles de Gaulle", ville= "Roissy", pays="France")
    aeroport2 = Aeroport(nom_aeroport = "Aéroport de Londres-Heathrow", ville= "Hounslow", pays="Royaume-Uni")
    aeroport3 = Aeroport(nom_aeroport = "Aéroport de Francfort", ville= "Francfort", pays="Allemagne")
    db.session.add(companie1)
    db.session.add(companie2)
    db.session.add(companie3)
    db.session.add(aeroport1)
    db.session.add(aeroport2)
    db.session.add(aeroport3)
    db.session.commit()
    localiser1  = Localiser(id_aeroport=1, id_companie=1)
    localiser2  = Localiser(id_aeroport=2, id_companie=2)
    localiser3  = Localiser(id_aeroport=2, id_companie=1)
    localiser4  = Localiser(id_aeroport=3, id_companie=3)
    db.session.add(localiser1)
    db.session.add(localiser2)
    db.session.add(localiser3)
    db.session.add(localiser4)
