from .extensions import db
from .models import *
from .myapp import app
from datetime import datetime

@app.cli.command()
def syncdb():
    db.create_all()
    db.session.query(Compagnie).delete()
    db.session.query(Aeroport).delete()
    db.session.query(Localiser).delete()
    db.session.query(Terminal).delete()
    db.session.query(Vol).delete()
    compagnie1 = Compagnie(nom_comp = "Air France")
    compagnie2 = Compagnie(nom_comp = "Corendon")
    compagnie3 = Compagnie(nom_comp = "Corsair")
    compagnie4 = Compagnie(nom_comp = "Ryanair")
    compagnie5 = Compagnie(nom_comp = "EasyJet")
    compagnie6 = Compagnie(nom_comp = "Lufthansa")
    compagnie7 = Compagnie(nom_comp = "British Airways")
    compagnie8 = Compagnie(nom_comp = "KLM")
    compagnie9 = Compagnie(nom_comp = "Emirates")
    compagnie10 = Compagnie(nom_comp = "Qatar Airways")
    compagnie11 = Compagnie(nom_comp = "Turkish Airlines")
    compagnie12 = Compagnie(nom_comp = "Delta Air Lines")
    compagnie13 = Compagnie(nom_comp = "United Airlines")
    compagnie14 = Compagnie(nom_comp = "American Airlines")
    compagnie15 = Compagnie(nom_comp = "Air Canada")
    aeroport1 = Aeroport(nom_aeroport = "Charles de Gaulle", ville= "Roissy", pays="France")
    aeroport2 = Aeroport(nom_aeroport = "Aéroport de Londres-Heathrow", ville= "Hounslow", pays="Royaume-Uni")
    aeroport3 = Aeroport(nom_aeroport = "Aéroport de Francfort", ville= "Francfort", pays="Allemagne")
    aeroport4 = Aeroport(nom_aeroport = "Aéroport de Dubaï", ville= "Dubaï", pays="Émirats arabes unis")
    aeroport5 = Aeroport(nom_aeroport = "Aéroport de New York-JFK", ville= "New York", pays="États-Unis")
    aeroport6 = Aeroport(nom_aeroport = "Aéroport de Tokyo-Haneda", ville= "Tokyo", pays="Japon")
    aeroport7 = Aeroport(nom_aeroport = "Aéroport de Sydney", ville= "Sydney", pays="Australie")
    aeroport8 = Aeroport(nom_aeroport = "Aéroport de Toronto-Pearson", ville= "Toronto", pays="Canada")
    aeroport9 = Aeroport(nom_aeroport = "Aéroport de São Paulo-Guarulhos", ville= "São Paulo", pays="Brésil")
    aeroport10 = Aeroport(nom_aeroport = "Aéroport de Moscou-Sheremetyevo", ville= "Moscou", pays="Russie")
    aeroport11 = Aeroport(nom_aeroport = "Aéroport de Mumbai-Chhatrapati Shivaji", ville= "Mumbai", pays="Inde")
    aeroport12 = Aeroport(nom_aeroport = "Aéroport de Mexico-Benito Juárez", ville= "Mexico", pays="Mexique")
    aeroport13 = Aeroport(nom_aeroport = "Aéroport de Johannesburg-OR Tambo", ville= "Johannesburg", pays="Afrique du Sud")
    aeroport14 = Aeroport(nom_aeroport = "Aéroport de Singapour-Changi", ville= "Singapour", pays="Singapour")
    aeroport15 = Aeroport(nom_aeroport = "Aéroport de Hong Kong", ville= "Hong Kong", pays="Chine")
    db.session.add(compagnie1)
    db.session.add(compagnie2)
    db.session.add(compagnie3)
    db.session.add(compagnie4)
    db.session.add(compagnie5)
    db.session.add(compagnie6)
    db.session.add(compagnie7)
    db.session.add(compagnie8)
    db.session.add(compagnie9)
    db.session.add(compagnie10)
    db.session.add(compagnie11)
    db.session.add(compagnie12)
    db.session.add(compagnie13)
    db.session.add(compagnie14)
    db.session.add(compagnie15)
    db.session.add(aeroport1)
    db.session.add(aeroport2)
    db.session.add(aeroport3)
    db.session.add(aeroport4)
    db.session.add(aeroport5)
    db.session.add(aeroport6)
    db.session.add(aeroport7)
    db.session.add(aeroport8)
    db.session.add(aeroport9)
    db.session.add(aeroport10)
    db.session.add(aeroport11)
    db.session.add(aeroport12)
    db.session.add(aeroport13)
    db.session.add(aeroport14)
    db.session.add(aeroport15)
    db.session.commit()
    localiser1  = Localiser(id_aeroport=1, id_compagnie=1)
    localiser2  = Localiser(id_aeroport=2, id_compagnie=2)
    localiser3  = Localiser(id_aeroport=2, id_compagnie=1)
    localiser4  = Localiser(id_aeroport=3, id_compagnie=3)
    localiser5 = Localiser(id_aeroport=4, id_compagnie=9)
    localiser6 = Localiser(id_aeroport=5, id_compagnie=13)
    localiser7 = Localiser(id_aeroport=5, id_compagnie=14)
    localiser8 = Localiser(id_aeroport=6, id_compagnie=12)
    localiser9 = Localiser(id_aeroport=7, id_compagnie=7)
    localiser10 = Localiser(id_aeroport=8, id_compagnie=4)
    localiser11 = Localiser(id_aeroport=8, id_compagnie=5)
    localiser12 = Localiser(id_aeroport=9, id_compagnie=11)
    localiser13 = Localiser(id_aeroport=9, id_compagnie=5)
    localiser14 = Localiser(id_aeroport=10, id_compagnie=9)
    localiser15 = Localiser(id_aeroport=10, id_compagnie=4)
    localiser16 = Localiser(id_aeroport=11, id_compagnie=9)
    localiser17 = Localiser(id_aeroport=11, id_compagnie=10)
    localiser18 = Localiser(id_aeroport=11, id_compagnie=11)
    localiser19 = Localiser(id_aeroport=12, id_compagnie=2)    
    localiser20 = Localiser(id_aeroport=12, id_compagnie=15)    
    localiser21 = Localiser(id_aeroport=12, id_compagnie=4)
    localiser22 = Localiser(id_aeroport=13, id_compagnie=11)    
    localiser23 = Localiser(id_aeroport=13, id_compagnie=1)    
    localiser24 = Localiser(id_aeroport=13, id_compagnie=8)  
    localiser25 = Localiser(id_aeroport=14, id_compagnie=6)  
    localiser26 = Localiser(id_aeroport=14, id_compagnie=10)  
    localiser27 = Localiser(id_aeroport=15, id_compagnie=12)
    localiser28 = Localiser(id_aeroport=15, id_compagnie=15)
    db.session.add(localiser1)
    db.session.add(localiser2)
    db.session.add(localiser3)
    db.session.add(localiser4)
    db.session.add(localiser5)
    db.session.add(localiser6)
    db.session.add(localiser7)
    db.session.add(localiser8)
    db.session.add(localiser9)
    db.session.add(localiser10)
    db.session.add(localiser11)
    db.session.add(localiser12)
    db.session.add(localiser13)
    db.session.add(localiser14)
    db.session.add(localiser15)
    db.session.add(localiser16)
    db.session.add(localiser17)
    db.session.add(localiser18)
    db.session.add(localiser19)
    db.session.add(localiser20)
    db.session.add(localiser21)
    db.session.add(localiser22)
    db.session.add(localiser23)
    db.session.add(localiser24)
    db.session.add(localiser25)
    db.session.add(localiser26)
    db.session.add(localiser27)
    db.session.add(localiser28)
    db.session.commit()
    terminal1 = Terminal(nom_terminal = "Terminal 1", id_aeroport=1)
    terminal2 = Terminal(nom_terminal = "Terminal 2A", id_aeroport=1)
    terminal3 = Terminal(nom_terminal = "Terminal 2B", id_aeroport=1)
    terminal4 = Terminal(nom_terminal = "Terminal 2C", id_aeroport=1)
    terminal5 = Terminal(nom_terminal = "Terminal 2", id_aeroport=2)
    terminal6 = Terminal(nom_terminal = "Terminal 3", id_aeroport=2)
    terminal7 = Terminal(nom_terminal = "Terminal 4", id_aeroport=2)
    terminal8 = Terminal(nom_terminal = "Terminal 5", id_aeroport=2)
    terminal9 = Terminal(nom_terminal = "Terminal 1", id_aeroport=3)
    terminal10 = Terminal(nom_terminal = "Terminal 2", id_aeroport=3)
    terminal11 = Terminal(nom_terminal = "Terminal 1", id_aeroport=4)
    terminal12 = Terminal(nom_terminal = "Terminal 2", id_aeroport=4)
    terminal13 = Terminal(nom_terminal = "Terminal 3", id_aeroport=4)
    terminal14 = Terminal(nom_terminal = "Concourse A", id_aeroport=4)
    terminal15 = Terminal(nom_terminal = "Terminal 1", id_aeroport=5)
    terminal16 = Terminal(nom_terminal = "Terminal 2", id_aeroport=5)
    terminal17 = Terminal(nom_terminal = "Terminal 4", id_aeroport=5)
    terminal18 = Terminal(nom_terminal = "Terminal 5", id_aeroport=5)
    terminal19 = Terminal(nom_terminal = "Terminal 1", id_aeroport=6)
    terminal20 = Terminal(nom_terminal = "Terminal 2", id_aeroport=6)
    terminal21 = Terminal(nom_terminal = "Terminal 3", id_aeroport=6)
    terminal22 = Terminal(nom_terminal = "Terminal 4", id_aeroport=6)
    terminal23 = Terminal(nom_terminal = "Terminal 1", id_aeroport=7)
    terminal24 = Terminal(nom_terminal = "Terminal 2", id_aeroport=7)
    terminal25 = Terminal(nom_terminal = "Terminal 3", id_aeroport=7)
    terminal26 = Terminal(nom_terminal = "Terminal 1", id_aeroport=8)
    terminal27 = Terminal(nom_terminal = "Terminal 2", id_aeroport=8)
    terminal28 = Terminal(nom_terminal = "Terminal 3", id_aeroport=8)
    terminal29 = Terminal(nom_terminal = "Terminal 1", id_aeroport=9)
    terminal30 = Terminal(nom_terminal = "Terminal 2", id_aeroport=9)
    terminal31 = Terminal(nom_terminal = "Terminal 3", id_aeroport=9)
    terminal32 = Terminal(nom_terminal = "Terminal A", id_aeroport=10)
    terminal33 = Terminal(nom_terminal = "Terminal B", id_aeroport=10)
    terminal34 = Terminal(nom_terminal = "Terminal C", id_aeroport=10)
    terminal35 = Terminal(nom_terminal = "Terminal 1", id_aeroport=11)
    terminal36 = Terminal(nom_terminal = "Terminal 2", id_aeroport=11)
    terminal37 = Terminal(nom_terminal = "Terminal 3", id_aeroport=11)
    terminal38 = Terminal(nom_terminal = "Terminal 1", id_aeroport=12)
    terminal39 = Terminal(nom_terminal = "Terminal 2", id_aeroport=12)
    terminal40 = Terminal(nom_terminal = "Terminal A", id_aeroport=13)
    terminal41 = Terminal(nom_terminal = "Terminal B", id_aeroport=13)
    terminal42 = Terminal(nom_terminal = "Terminal C", id_aeroport=13)
    terminal43 = Terminal(nom_terminal = "Terminal 1", id_aeroport=14)
    terminal44 = Terminal(nom_terminal = "Terminal 2", id_aeroport=14)
    terminal45 = Terminal(nom_terminal = "Terminal 3", id_aeroport=14)
    terminal46 = Terminal(nom_terminal = "Terminal 4", id_aeroport=14)
    terminal47 = Terminal(nom_terminal = "Terminal 1", id_aeroport=15)
    terminal48 = Terminal(nom_terminal = "Terminal 2", id_aeroport=15)
    terminal49 = Terminal(nom_terminal = "Terminal 3", id_aeroport=15)
    db.session.add(terminal1)
    db.session.add(terminal2)
    db.session.add(terminal3)
    db.session.add(terminal4)
    db.session.add(terminal5)
    db.session.add(terminal6)
    db.session.add(terminal7)
    db.session.add(terminal8)
    db.session.add(terminal9)
    db.session.add(terminal10)
    db.session.add(terminal11)
    db.session.add(terminal12)
    db.session.add(terminal13)
    db.session.add(terminal14)
    db.session.add(terminal15)
    db.session.add(terminal16)
    db.session.add(terminal17)
    db.session.add(terminal18)
    db.session.add(terminal19)
    db.session.add(terminal20)
    db.session.add(terminal21)
    db.session.add(terminal22)
    db.session.add(terminal23)
    db.session.add(terminal24)
    db.session.add(terminal25)
    db.session.add(terminal26)
    db.session.add(terminal27)
    db.session.add(terminal28)
    db.session.add(terminal29)
    db.session.add(terminal30)
    db.session.add(terminal31)
    db.session.add(terminal32)
    db.session.add(terminal33)
    db.session.add(terminal34)
    db.session.add(terminal35)
    db.session.add(terminal36)
    db.session.add(terminal37)
    db.session.add(terminal38)
    db.session.add(terminal39)
    db.session.add(terminal40)
    db.session.add(terminal41)
    db.session.add(terminal42)
    db.session.add(terminal43)
    db.session.add(terminal44)
    db.session.add(terminal45)
    db.session.add(terminal46)
    db.session.add(terminal47)
    db.session.add(terminal48)
    db.session.add(terminal49)
    db.session.commit()
    vol1 = Vol(nom_vol = "AF123", id_compagnie=1, id_terminal_depart=1, id_terminal_arrivee=5, date_heure_depart=datetime.strptime("2024-07-01 08:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-01 10:00:00", "%Y-%m-%d %H:%M:%S")) 
    vol2 = Vol(nom_vol = "AF456", id_compagnie=1, id_terminal_depart=2, id_terminal_arrivee=6, date_heure_depart=datetime.strptime("2024-07-01 09:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-01 11:00:00", "%Y-%m-%d %H:%M:%S"))
    vol3 = Vol(nom_vol = "CO789", id_compagnie=2, id_terminal_depart=5, id_terminal_arrivee=38, date_heure_depart=datetime.strptime("2024-07-01 10:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-01 12:00:00", "%Y-%m-%d %H:%M:%S"))
    vol4 = Vol(nom_vol = "CO101", id_compagnie=2, id_terminal_depart=39, id_terminal_arrivee=6, date_heure_depart=datetime.strptime("2024-07-01 11:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-01 13:00:00", "%Y-%m-%d %H:%M:%S"))
    vol5 = Vol(nom_vol = "CO112", id_compagnie=3, id_terminal_depart=9, id_terminal_arrivee=10, date_heure_depart=datetime.strptime("2024-07-01 12:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-01 14:00:00", "%Y-%m-%d %H:%M:%S"))
    vol6 = Vol(nom_vol = "CO131", id_compagnie=3, id_terminal_depart=10, id_terminal_arrivee=9, date_heure_depart=datetime.strptime("2024-07-01 13:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-01 15:00:00", "%Y-%m-%d %H:%M:%S"))
    vol7 = Vol(nom_vol = "RA201", id_compagnie=4, id_terminal_depart=26, id_terminal_arrivee=32, date_heure_depart=datetime.strptime("2024-07-02 07:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-02 10:00:00", "%Y-%m-%d %H:%M:%S"))
    vol8 = Vol(nom_vol = "RA202", id_compagnie=4, id_terminal_depart=34, id_terminal_arrivee=38, date_heure_depart=datetime.strptime("2024-07-02 11:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-02 14:00:00", "%Y-%m-%d %H:%M:%S"))
    vol9 = Vol(nom_vol = "EJ301", id_compagnie=5, id_terminal_depart=26, id_terminal_arrivee=27, date_heure_depart=datetime.strptime("2024-07-02 08:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-02 09:00:00", "%Y-%m-%d %H:%M:%S"))
    vol10 = Vol(nom_vol = "EJ302", id_compagnie=5, id_terminal_depart=28, id_terminal_arrivee=26, date_heure_depart=datetime.strptime("2024-07-02 10:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-02 11:00:00", "%Y-%m-%d %H:%M:%S"))
    vol11 = Vol(nom_vol = "LU401", id_compagnie=6, id_terminal_depart=43, id_terminal_arrivee=44, date_heure_depart=datetime.strptime("2024-07-02 06:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-02 07:30:00", "%Y-%m-%d %H:%M:%S"))
    vol12 = Vol(nom_vol = "LU402", id_compagnie=6, id_terminal_depart=46, id_terminal_arrivee=43, date_heure_depart=datetime.strptime("2024-07-02 13:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-02 14:30:00", "%Y-%m-%d %H:%M:%S"))
    vol13 = Vol(nom_vol = "BA501", id_compagnie=7, id_terminal_depart=23, id_terminal_arrivee=24, date_heure_depart=datetime.strptime("2024-07-02 09:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-02 10:00:00", "%Y-%m-%d %H:%M:%S"))
    vol14 = Vol(nom_vol = "BA502", id_compagnie=7, id_terminal_depart=25, id_terminal_arrivee=23, date_heure_depart=datetime.strptime("2024-07-02 14:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-02 15:00:00", "%Y-%m-%d %H:%M:%S"))
    vol15 = Vol(nom_vol = "KL601", id_compagnie=8, id_terminal_depart=40, id_terminal_arrivee=41, date_heure_depart=datetime.strptime("2024-07-02 05:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-02 06:30:00", "%Y-%m-%d %H:%M:%S"))
    vol16 = Vol(nom_vol = "KL602", id_compagnie=8, id_terminal_depart=42, id_terminal_arrivee=40, date_heure_depart=datetime.strptime("2024-07-02 16:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-02 17:30:00", "%Y-%m-%d %H:%M:%S"))
    vol17 = Vol(nom_vol = "EM701", id_compagnie=9, id_terminal_depart=11, id_terminal_arrivee=32, date_heure_depart=datetime.strptime("2024-07-03 02:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-03 06:00:00", "%Y-%m-%d %H:%M:%S"))
    vol18 = Vol(nom_vol = "EM702", id_compagnie=9, id_terminal_depart=35, id_terminal_arrivee=13, date_heure_depart=datetime.strptime("2024-07-03 08:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-03 12:00:00", "%Y-%m-%d %H:%M:%S"))
    vol19 = Vol(nom_vol = "QA801", id_compagnie=10, id_terminal_depart=35, id_terminal_arrivee=43, date_heure_depart=datetime.strptime("2024-07-03 10:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-03 14:00:00", "%Y-%m-%d %H:%M:%S"))
    vol20 = Vol(nom_vol = "QA802", id_compagnie=10, id_terminal_depart=46, id_terminal_arrivee=37, date_heure_depart=datetime.strptime("2024-07-03 15:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-03 19:00:00", "%Y-%m-%d %H:%M:%S"))
    vol21 = Vol(nom_vol = "TA901", id_compagnie=11, id_terminal_depart=29, id_terminal_arrivee=35, date_heure_depart=datetime.strptime("2024-07-03 12:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-03 16:00:00", "%Y-%m-%d %H:%M:%S"))
    vol22 = Vol(nom_vol = "TA902", id_compagnie=11, id_terminal_depart=37, id_terminal_arrivee=40, date_heure_depart=datetime.strptime("2024-07-03 18:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-03 22:00:00", "%Y-%m-%d %H:%M:%S"))
    vol23 = Vol(nom_vol = "DA001", id_compagnie=12, id_terminal_depart=19, id_terminal_arrivee=47, date_heure_depart=datetime.strptime("2024-07-04 08:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-04 12:00:00", "%Y-%m-%d %H:%M:%S"))
    vol24 = Vol(nom_vol = "DA002", id_compagnie=12, id_terminal_depart=49, id_terminal_arrivee=22, date_heure_depart=datetime.strptime("2024-07-04 14:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-04 18:00:00", "%Y-%m-%d %H:%M:%S"))
    vol25 = Vol(nom_vol = "UA101", id_compagnie=13, id_terminal_depart=15, id_terminal_arrivee=16, date_heure_depart=datetime.strptime("2024-07-04 07:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-04 08:00:00", "%Y-%m-%d %H:%M:%S"))
    vol26 = Vol(nom_vol = "UA102", id_compagnie=13, id_terminal_depart=18, id_terminal_arrivee=15, date_heure_depart=datetime.strptime("2024-07-04 17:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-04 18:00:00", "%Y-%m-%d %H:%M:%S"))
    vol27 = Vol(nom_vol = "AA201", id_compagnie=14, id_terminal_depart=15, id_terminal_arrivee=17, date_heure_depart=datetime.strptime("2024-07-04 09:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-04 10:00:00", "%Y-%m-%d %H:%M:%S"))
    vol28 = Vol(nom_vol = "AA202", id_compagnie=14, id_terminal_depart=18, id_terminal_arrivee=16, date_heure_depart=datetime.strptime("2024-07-04 18:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-04 19:00:00", "%Y-%m-%d %H:%M:%S"))
    vol29 = Vol(nom_vol = "AC301", id_compagnie=15, id_terminal_depart=38, id_terminal_arrivee=47, date_heure_depart=datetime.strptime("2024-07-04 10:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-04 14:00:00", "%Y-%m-%d %H:%M:%S"))
    vol30 = Vol(nom_vol = "AC302", id_compagnie=15, id_terminal_depart=49, id_terminal_arrivee=39, date_heure_depart=datetime.strptime("2024-07-04 20:00:00", "%Y-%m-%d %H:%M:%S"), date_heure_arrivee=datetime.strptime("2024-07-05 00:00:00", "%Y-%m-%d %H:%M:%S"))
    db.session.add(vol1)
    db.session.add(vol2)   
    db.session.add(vol3)
    db.session.add(vol4)
    db.session.add(vol5)
    db.session.add(vol6)
    db.session.add(vol7)
    db.session.add(vol8)
    db.session.add(vol9)
    db.session.add(vol10)
    db.session.add(vol11)
    db.session.add(vol12)
    db.session.add(vol13)
    db.session.add(vol14)
    db.session.add(vol15)
    db.session.add(vol16)
    db.session.add(vol17)
    db.session.add(vol18)
    db.session.add(vol19)
    db.session.add(vol20)
    db.session.add(vol21)
    db.session.add(vol22)
    db.session.add(vol23)
    db.session.add(vol24)
    db.session.add(vol25)
    db.session.add(vol26)
    db.session.add(vol27)
    db.session.add(vol28)
    db.session.add(vol29)
    db.session.add(vol30)
    db.session.commit()
